# Generated by Django 3.1 on 2020-08-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pj_name', models.CharField(max_length=255, verbose_name='BoM Name')),
                ('quantity', models.PositiveIntegerField()),
                ('pj_type', models.CharField(max_length=255)),
                ('pj_language', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'project_model',
            },
        ),
    ]
